### ISSUE TITLE
libtensorflow.so.1: cannot open shared object file: No such file or director

### ISSUE THREAD

**Issue by utrobinmv** [DoubangoTelecom/ultimateCreditCard-SDK#28]
When running samples on python 3.7.9. Writes an error.

`./run_linux_x64.sh
Traceback (most recent call last):
  File "recognizer.py", line 24, in <module>
    import ultimateCreditCardSdk
  File "/home/joefox/Documents/00000001/ultimateCreditCard-SDK/python/ultimateCreditCardSdk.py", line 26, in <module>
    _ultimateCreditCardSdk = swig_import_helper()
  File "/home/joefox/Documents/00000001/ultimateCreditCard-SDK/python/ultimateCreditCardSdk.py", line 22, in swig_import_helper
    _mod = imp.load_module('_ultimateCreditCardSdk', fp, pathname, description)
  File "/home/joefox/.pyenv/versions/3.7.9/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/joefox/.pyenv/versions/3.7.9/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libtensorflow.so.1: cannot open shared object file: No such file or directory`

**Comment by DoubangoTelecom** [comment]
https://github.com/DoubangoTelecom/ultimateCreditCard-SDK/blob/master/samples/c%2B%2B/README.md#gpu-acceleration-tensorflow-linux
